# Site settings
title: Yuanduo He's Autobiograph 
email: 694912391@qq.com
description: > # this means to ignore newlines until "baseurl:"
  A peaceful place to write down life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: none
github_username:  rubyhyd

# Build settings
markdown: kramdown
